### ISSUE TITLE
Add hidden field to manifest.json to hide the extension from about:addons

### ISSUE THREAD

**Issue by juliandescottes** [mozilla-extensions/devtools-adb-extension#8]
Feature was added for privileged addons in https://bugzilla.mozilla.org/show_bug.cgi?id=1365349

**Comment by rpl** [comment]
> Feature was added for privileged addons in https://bugzilla.mozilla.org/show_bug.cgi?id=1365349

hey @juliandescottes I kind of recall we were briefly discussing about this in [Bug 1533150 comment 6](https://bugzilla.mozilla.org/show_bug.cgi?id=1533150#c6) and [Bug 1533150 comment 8](https://bugzilla.mozilla.org/show_bug.cgi?id=1533150#c8) some time ago, if we don't have and don't plan to have some other ways to let users to uninstall the adb addon if they need/want to then it would be better to don't hide the adb addon.

I'm pasting a comment with that discussion here so that we don't forget about it, but if we don't provide to the user any other way to uninstall the adb addon and we don't plan to add it, then maybe it may be reasonable to wontfix and close this issue, wdyt?

**Comment by willdurand** [comment]
@juliandescottes is this still relevant? Like Luca, I don't think we should hide the extension.

**Comment by juliandescottes** [comment]
I agree, I was about to close this yesterday. I don't think it makes sense to hide this.
